# Generated by Django 4.1.1 on 2022-10-01 17:53

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_publicuser_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ph_no',
            field=models.CharField(max_length=10, unique=True, validators=[accounts.validators.validate_contact_number]),
        ),
    ]
