# Generated by Django 4.1.1 on 2022-10-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(default='New Delhi', max_length=255),
        ),
        migrations.AddField(
            model_name='hospital',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
