# Generated by Django 4.1.1 on 2022-10-01 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_website_hospital_city_hospital_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publicUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
