# Generated by Django 4.1.1 on 2022-10-01 16:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers_publicuser_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('bloodType', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('A-', 'A-'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NA', 'NA')], default='NA', max_length=3)),
                ('age', models.IntegerField(default=-1)),
                ('sex', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER'), ('NA', 'NOT AVAILABLE')], default='NA', max_length=2)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospital')),
                ('organType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmodels.organtype')),
            ],
        ),
    ]
